-- ════════════════════════════════════════════════════════════
-- Ninja Teacher — Database Schema (school_jobs)
-- ملاحظة: الـ Backend بيعمل sequelize.sync تلقائيًا عند الإقلاع،
--         فاستيراد الملف ده اختياري. يكفي إنشاء database فاضية اسمها school_jobs.
-- ════════════════════════════════════════════════════════════
CREATE DATABASE IF NOT EXISTS school_jobs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE school_jobs;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `Admins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('super_admin','moderator') NOT NULL DEFAULT 'moderator',
  `is_active` tinyint(1) DEFAULT 1,
  `last_login` datetime DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `email_2` (`email`),
  UNIQUE KEY `email_3` (`email`),
  UNIQUE KEY `email_4` (`email`),
  UNIQUE KEY `email_5` (`email`),
  UNIQUE KEY `email_6` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Application` (
  `Teacher_ID` int(11) NOT NULL,
  `Job_ID` int(11) NOT NULL,
  `Apply_Date` date DEFAULT NULL,
  `Big5_Score` decimal(5,2) DEFAULT NULL,
  `Status` enum('pending','interview','accepted','rejected') NOT NULL DEFAULT 'pending',
  `School_ID` int(11) DEFAULT NULL COMMENT 'FK to Post.School_ID — identifies the correct job post',
  PRIMARY KEY (`Teacher_ID`,`Job_ID`),
  KEY `Job_ID` (`Job_ID`),
  KEY `application__school__i_d__job__i_d` (`School_ID`,`Job_ID`),
  KEY `application__teacher__i_d` (`Teacher_ID`),
  KEY `application__status` (`Status`),
  CONSTRAINT `Application_ibfk_1` FOREIGN KEY (`Teacher_ID`) REFERENCES `Teacher` (`Teacher_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Assessments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` int(11) NOT NULL,
  `answers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`answers`)),
  `decision` enum('ACCEPTED','REJECTED') DEFAULT NULL,
  `confidence` decimal(5,1) DEFAULT NULL,
  `raw_score` decimal(5,1) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `positive_factors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`positive_factors`)),
  `negative_factors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`negative_factors`)),
  `suggestions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`suggestions`)),
  `status` enum('pending','completed','failed') DEFAULT 'pending',
  `error_message` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Certifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` int(11) NOT NULL,
  `title` varchar(200) NOT NULL,
  `issuing_org` varchar(200) DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `credential_id` varchar(100) DEFAULT NULL,
  `credential_url` varchar(500) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ContactMessages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `subject` varchar(200) NOT NULL,
  `message` text NOT NULL,
  `status` enum('new','read','replied') DEFAULT 'new',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Education` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` int(11) NOT NULL,
  `degree` varchar(100) NOT NULL,
  `institution` varchar(200) NOT NULL,
  `field` varchar(100) DEFAULT NULL,
  `start_year` int(11) DEFAULT NULL,
  `end_year` int(11) DEFAULT NULL,
  `grade` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `payment_id` int(11) NOT NULL,
  `subscription_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(10) DEFAULT 'EGP',
  `plan_name` varchar(100) NOT NULL,
  `billing_period_start` datetime DEFAULT NULL,
  `billing_period_end` datetime DEFAULT NULL,
  `status` enum('issued','void') DEFAULT 'issued',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`),
  UNIQUE KEY `invoice_number_2` (`invoice_number`),
  UNIQUE KEY `invoice_number_3` (`invoice_number`),
  UNIQUE KEY `invoice_number_4` (`invoice_number`),
  UNIQUE KEY `invoice_number_5` (`invoice_number`),
  UNIQUE KEY `invoice_number_6` (`invoice_number`),
  KEY `subscription_id` (`subscription_id`),
  KEY `payment_id` (`payment_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `Invoices_ibfk_12` FOREIGN KEY (`payment_id`) REFERENCES `Payments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Invoices_ibfk_13` FOREIGN KEY (`user_id`) REFERENCES `Teacher` (`Teacher_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Invoices_ibfk_2` FOREIGN KEY (`subscription_id`) REFERENCES `Subscriptions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Job` (
  `Job_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(100) NOT NULL,
  `Required_Experience` int(11) DEFAULT NULL,
  `Required_Qualification` varchar(200) DEFAULT NULL,
  `Salary_Range` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Job_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender_id` int(11) NOT NULL,
  `sender_name` varchar(200) NOT NULL,
  `receiver_id` int(11) NOT NULL,
  `subject` varchar(200) DEFAULT NULL,
  `body` text NOT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `job_id` int(11) DEFAULT NULL,
  `job_title` varchar(100) DEFAULT NULL,
  `type` enum('general','interview_invite','offer','rejection') DEFAULT 'general',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Notifications` (
  `Notification_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Teacher_ID` int(11) NOT NULL,
  `Type` varchar(100) NOT NULL,
  `Title` varchar(255) NOT NULL,
  `Message` text NOT NULL,
  `IsRead` tinyint(1) DEFAULT 0,
  `Related_ID` int(11) DEFAULT NULL COMMENT 'Job_ID, subscription id, or other reference depending on Type',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `Related_School_ID` int(11) DEFAULT NULL COMMENT 'Post.School_ID when notification is job/application related',
  PRIMARY KEY (`Notification_ID`),
  KEY `notifications__teacher__i_d` (`Teacher_ID`),
  KEY `notifications__teacher__i_d__is_read` (`Teacher_ID`,`IsRead`),
  KEY `notifications__type` (`Type`),
  CONSTRAINT `Notifications_ibfk_1` FOREIGN KEY (`Teacher_ID`) REFERENCES `Teacher` (`Teacher_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subscription_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(10) DEFAULT 'EGP',
  `provider` enum('instapay','vodafone_cash','orange_cash','manual','free') NOT NULL,
  `status` enum('pending','paid','failed','expired','refunded') NOT NULL DEFAULT 'pending',
  `transaction_ref` varchar(100) NOT NULL,
  `provider_ref` varchar(200) DEFAULT NULL,
  `provider_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`provider_response`)),
  `paid_at` datetime DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `payment_proof` varchar(500) DEFAULT NULL,
  `failure_reason` varchar(500) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `transaction_ref` (`transaction_ref`),
  UNIQUE KEY `transaction_ref_2` (`transaction_ref`),
  UNIQUE KEY `transaction_ref_3` (`transaction_ref`),
  UNIQUE KEY `transaction_ref_4` (`transaction_ref`),
  UNIQUE KEY `transaction_ref_5` (`transaction_ref`),
  UNIQUE KEY `transaction_ref_6` (`transaction_ref`),
  KEY `subscription_id` (`subscription_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `Payments_ibfk_11` FOREIGN KEY (`subscription_id`) REFERENCES `Subscriptions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Payments_ibfk_12` FOREIGN KEY (`user_id`) REFERENCES `Teacher` (`Teacher_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Post` (
  `School_ID` int(11) NOT NULL,
  `Job_ID` int(11) NOT NULL,
  `Title` varchar(100) NOT NULL,
  `Specialization` varchar(100) DEFAULT NULL,
  `Required_Experience` int(11) DEFAULT 0,
  `Content` text DEFAULT NULL,
  `Description` text DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `Location` varchar(200) DEFAULT NULL,
  `Subjects` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Subjects`)),
  `Job_Type` enum('full-time','part-time','freelance','contract') DEFAULT 'full-time',
  `Required_Qualifications` text DEFAULT NULL,
  `Start_Date` date DEFAULT NULL,
  `Deadline` date DEFAULT NULL,
  `Salary_Range` varchar(100) DEFAULT NULL,
  `Responsibilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Responsibilities`)),
  `Requirements` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Requirements`)),
  `Benefits` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Benefits`)),
  `Teaching_Style` enum('strict','flexible','structured','free-flowing') DEFAULT NULL,
  `Classroom_Energy` enum('calm','energetic','collaborative','playful','balanced') DEFAULT NULL,
  `Leadership_Style` enum('leader','supporter','collaborator','mentor') DEFAULT NULL,
  `Communication_Style` enum('direct','empathetic','formal','casual') DEFAULT NULL,
  `Problem_Solving` enum('analytical','creative','practical','innovative') DEFAULT NULL,
  `Status` enum('active','closed','draft') DEFAULT 'active',
  `Applicants_Count` int(11) DEFAULT 0,
  `School_Rating` decimal(3,2) DEFAULT 0.00,
  PRIMARY KEY (`School_ID`,`Job_ID`),
  KEY `Job_ID` (`Job_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Reviews` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reviewer_id` int(11) NOT NULL,
  `reviewer_name` varchar(200) NOT NULL,
  `reviewer_type` enum('school','teacher') DEFAULT 'school',
  `teacher_id` int(11) NOT NULL,
  `rating` decimal(2,1) NOT NULL,
  `comment` text DEFAULT NULL,
  `job_title` varchar(100) DEFAULT NULL,
  `job_id` int(11) DEFAULT NULL,
  `is_visible` tinyint(1) DEFAULT 1,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `teacher_id` (`teacher_id`),
  CONSTRAINT `Reviews_ibfk_1` FOREIGN KEY (`teacher_id`) REFERENCES `Teacher` (`Teacher_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `SavedJobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Teacher_ID` int(11) NOT NULL,
  `School_ID` int(11) NOT NULL,
  `Job_ID` int(11) NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `saved_jobs__teacher__i_d__school__i_d__job__i_d` (`Teacher_ID`,`School_ID`,`Job_ID`),
  KEY `saved_jobs__teacher__i_d` (`Teacher_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `School` (
  `School_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Location` varchar(200) DEFAULT NULL,
  `Type` varchar(50) DEFAULT NULL,
  `Phone` varchar(20) DEFAULT NULL,
  `Email` varchar(100) NOT NULL,
  PRIMARY KEY (`School_ID`),
  UNIQUE KEY `Email` (`Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `SubscriptionPlans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plan_key` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `target_role` enum('teacher','school') NOT NULL,
  `price_egp` decimal(10,2) NOT NULL DEFAULT 0.00,
  `duration_days` int(11) NOT NULL DEFAULT 30,
  `billing_cycle` enum('monthly','yearly','lifetime') DEFAULT 'monthly',
  `features` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`features`)),
  `max_applications` int(11) DEFAULT -1,
  `max_job_posts` int(11) DEFAULT -1,
  `is_active` tinyint(1) DEFAULT 1,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `plan_key` (`plan_key`),
  UNIQUE KEY `plan_key_2` (`plan_key`),
  UNIQUE KEY `plan_key_3` (`plan_key`),
  UNIQUE KEY `plan_key_4` (`plan_key`),
  UNIQUE KEY `plan_key_5` (`plan_key`),
  UNIQUE KEY `plan_key_6` (`plan_key`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `plan_id` int(11) NOT NULL,
  `status` enum('active','cancelled','expired','pending_payment') NOT NULL DEFAULT 'pending_payment',
  `started_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `cancelled_at` datetime DEFAULT NULL,
  `price_paid` decimal(10,2) DEFAULT NULL,
  `auto_renew` tinyint(1) DEFAULT 0,
  `notes` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `plan_id` (`plan_id`),
  CONSTRAINT `Subscriptions_ibfk_11` FOREIGN KEY (`user_id`) REFERENCES `Teacher` (`Teacher_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Subscriptions_ibfk_12` FOREIGN KEY (`plan_id`) REFERENCES `SubscriptionPlans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `Teacher` (
  `Teacher_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `Phone` varchar(20) DEFAULT NULL,
  `Date_of_Birth` date DEFAULT NULL,
  `Gender` varchar(10) DEFAULT NULL,
  `Qualifications` varchar(200) DEFAULT NULL,
  `Specialization` varchar(100) DEFAULT NULL,
  `Years_of_Experience` int(11) DEFAULT 0,
  `Big5_Score` decimal(5,2) DEFAULT NULL,
  `Image` varchar(500) DEFAULT NULL,
  `Role` enum('teacher','school') NOT NULL DEFAULT 'teacher',
  `Bio` text DEFAULT NULL,
  `Location` varchar(200) DEFAULT NULL,
  `Nationality` varchar(100) DEFAULT NULL,
  `CV_File` varchar(500) DEFAULT NULL COMMENT 'Public URL path e.g. /uploads/cvs/cv-123.pdf',
  `Profile_Completion` int(11) DEFAULT 0,
  `Big5_Scores` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Big5_Scores`)),
  `Average_Rating` decimal(3,2) DEFAULT 0.00,
  `Total_Reviews` int(11) DEFAULT 0,
  `School_Name` varchar(200) DEFAULT NULL,
  `School_Type` varchar(100) DEFAULT NULL,
  `School_Size` int(11) DEFAULT NULL,
  `Is_Available` tinyint(1) DEFAULT 1,
  `Job_Type_Preference` varchar(50) DEFAULT NULL,
  `Expected_Salary` varchar(100) DEFAULT NULL,
  `LinkedIn_URL` varchar(500) DEFAULT NULL,
  `Website_URL` varchar(500) DEFAULT NULL,
  `Reset_Token` varchar(255) DEFAULT NULL,
  `Reset_Token_Expiry` datetime DEFAULT NULL,
  PRIMARY KEY (`Teacher_ID`),
  UNIQUE KEY `Email` (`Email`),
  UNIQUE KEY `Email_2` (`Email`),
  UNIQUE KEY `Email_3` (`Email`),
  UNIQUE KEY `Email_4` (`Email`),
  UNIQUE KEY `Email_5` (`Email`),
  UNIQUE KEY `Email_6` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `WorkExperience` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` int(11) NOT NULL,
  `job_title` varchar(100) NOT NULL,
  `school_name` varchar(200) NOT NULL,
  `location` varchar(200) DEFAULT NULL,
  `subject` varchar(100) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `is_current` tinyint(1) DEFAULT 0,
  `description` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS=1;
