// ─── Design Tokens ────────────────────────────────────────────────────────────
export const gradientBg =
  "linear-gradient(135deg, #5d3bdc 0%, #b1008c 50%, #fd4ccb 100%)";

export const gradientText = {
  background: gradientBg,
  WebkitBackgroundClip: "text",
  WebkitTextFillColor: "transparent",
};

// ─── Initial Data ─────────────────────────────────────────────────────────────
export const INIT_TEACHERS = [
  {
    id: 1,
    initials: "SM",
    color: "#5d3bdc",
    bg: "#e6deff",
    name: "Sarah Miller",
    email: "sarah.m@example.com",
    skills: ["ESL", "IELTS"],
    exp: "6 Years",
    personality: "The Protagonist (ENFP)",
    sub: "Premium",
    subPeriod: "Yearly",
    status: "active",
  },
  {
    id: 2,
    initials: "DC",
    color: "#b1008c",
    bg: "#ffd8ec",
    name: "David Chen",
    email: "d.chen@example.com",
    skills: ["Physics", "Math"],
    exp: "4 Years",
    personality: "The Logistician (ISTJ)",
    sub: "Basic",
    subPeriod: "Monthly",
    status: "expired",
  },
  {
    id: 3,
    initials: "EL",
    color: "#8d4b00",
    bg: "#ffdcc3",
    name: "Elena Lucas",
    email: "elena.edu@example.com",
    skills: ["Primary Ed", "Montessori"],
    exp: "12 Years",
    personality: "The Giver (ENFJ)",
    sub: "Premium",
    subPeriod: "Yearly",
    status: "active",
  },
  {
    id: 4,
    initials: "JB",
    color: "#484555",
    bg: "#e5eeff",
    name: "James Brown",
    email: "j.brown@example.com",
    skills: ["History", "Social Studies"],
    exp: "8 Years",
    personality: "The Architect (INTJ)",
    sub: "Basic",
    subPeriod: "Monthly",
    status: "pending",
  },
  {
    id: 5,
    initials: "AR",
    color: "#5d3bdc",
    bg: "#e6deff",
    name: "Aisha Rahman",
    email: "a.rahman@example.com",
    skills: ["Arabic", "ESL"],
    exp: "3 Years",
    personality: "The Mentor (ENFJ)",
    sub: "Premium",
    subPeriod: "Yearly",
    status: "active",
  },
];

export const INIT_SCHOOLS = [
  {
    id: 1,
    initials: "GH",
    color: "#5d3bdc",
    bg: "#e6deff",
    name: "Greenwood High",
    city: "Berlin, Germany",
    type: "IB School",
    sub: "Gold",
    status: "active",
    teachers: 12,
    rating: 4.9,
  },
  {
    id: 2,
    initials: "NS",
    color: "#b1008c",
    bg: "#ffd8ec",
    name: "North Star Academy",
    city: "Munich, Germany",
    type: "STEAM Focus",
    sub: "Silver",
    status: "active",
    teachers: 8,
    rating: 4.7,
  },
  {
    id: 3,
    initials: "WA",
    color: "#8d4b00",
    bg: "#ffdcc3",
    name: "Westside Arts",
    city: "Hamburg, Germany",
    type: "Arts School",
    sub: "Gold",
    status: "active",
    teachers: 15,
    rating: 4.8,
  },
  {
    id: 4,
    initials: "BC",
    color: "#484555",
    bg: "#e5eeff",
    name: "Beacon College",
    city: "Frankfurt, Germany",
    type: "Comprehensive",
    sub: "Basic",
    status: "pending",
    teachers: 4,
    rating: 4.2,
  },
  {
    id: 5,
    initials: "RM",
    color: "#5d3bdc",
    bg: "#e6deff",
    name: "Royal Montessori",
    city: "Cologne, Germany",
    type: "Montessori",
    sub: "Silver",
    status: "active",
    teachers: 7,
    rating: 4.6,
  },
];

export const INIT_MATCHES = [
  {
    id: 1,
    t1: "GH",
    t2: "SJ",
    school: "Greenwood High",
    teacher: "Sarah Jenkins",
    score: 98,
    tags: ["Mathematics", "IB Curriculum"],
    insight:
      "Perfect skills alignment and complementary teaching philosophies detected.",
    status: "pending",
  },
  {
    id: 2,
    t1: "NS",
    t2: "DC",
    school: "North Star Academy",
    teacher: "David Chen",
    score: 94,
    tags: ["Physics", "Leadership"],
    insight:
      "High leadership compatibility score matches Senior Head of Science role.",
    status: "pending",
  },
  {
    id: 3,
    t1: "WA",
    t2: "ER",
    school: "Westside Arts",
    teacher: "Elena Rossi",
    score: 91,
    tags: ["Fine Arts", "Berlin-based"],
    insight:
      "Geographic proximity reduces relocation friction. Studio art is a direct match.",
    status: "approved",
  },
];

export const INIT_NOTIFICATIONS = [
  {
    id: 1,
    iconKey: "Shuffle",
    iconColor: "#5d3bdc",
    iconBg: "rgba(93,59,220,0.1)",
    title: "New Match Found",
    body: "AI engine found a 96% compatibility match between Beacon College and James Miller.",
    time: "5 min ago",
    unread: true,
    actions: ["Review Match", "Dismiss"],
  },
  {
    id: 2,
    iconKey: "Users",
    iconColor: "#b1008c",
    iconBg: "rgba(177,0,140,0.1)",
    title: "Teacher Application Pending",
    body: "Aisha Rahman completed her profile and is awaiting admin approval.",
    time: "1 hr ago",
    unread: true,
    actions: ["View Profile"],
  },
  {
    id: 3,
    iconKey: "CreditCard",
    iconColor: "#059669",
    iconBg: "rgba(5,150,105,0.1)",
    title: "Subscription Renewed",
    body: "Royal Montessori successfully renewed their Silver plan for another year.",
    time: "3 hrs ago",
    unread: false,
    actions: [],
  },
  {
    id: 4,
    iconKey: "Star",
    iconColor: "#d97706",
    iconBg: "rgba(217,119,6,0.1)",
    title: "New School Review",
    body: "Greenwood High left a 5-star review for Sarah Jenkins. Match #4421 closed.",
    time: "Yesterday",
    unread: false,
    actions: [],
  },
  {
    id: 5,
    iconKey: "Settings",
    iconColor: "#484555",
    iconBg: "rgba(72,69,85,0.1)",
    title: "System Maintenance Completed",
    body: "Scheduled maintenance window completed. All systems operating normally.",
    time: "2 days ago",
    unread: false,
    actions: [],
  },
];

export const INIT_FEEDBACK = [
  {
    id: 1,
    initials: "SJ",
    color: "#5d3bdc",
    bg: "#e6deff",
    name: "Sarah Jenkins",
    school: "Greenwood High",
    rating: 5,
    text: "Absolutely exceptional teacher. Her methodology transformed our students' engagement levels entirely.",
    time: "2 days ago",
    critical: false,
  },
  {
    id: 2,
    initials: "MC",
    color: "#b1008c",
    bg: "#ffd8ec",
    name: "Michael Chen",
    school: "North Star Academy",
    rating: 4,
    text: "Very professional and knowledgeable. Minor communication issues at the start but resolved quickly.",
    time: "4 days ago",
    critical: false,
  },
  {
    id: 3,
    initials: "ER",
    color: "#ba1a1a",
    bg: "#ffdad6",
    name: "Elena Rodriguez",
    school: "Westside Arts",
    rating: 2,
    text: "Unfortunately did not meet the school's expectations. Cultural fit was a significant challenge.",
    time: "1 week ago",
    critical: true,
  },
  {
    id: 4,
    initials: "LW",
    color: "#059669",
    bg: "rgba(5,150,105,0.1)",
    name: "Linda Wu",
    school: "Royal Montessori",
    rating: 5,
    text: "A perfect match from day one. Linda's Montessori expertise is exactly what our school needed.",
    time: "2 weeks ago",
    critical: false,
  },
];

export const EMPTY_TEACHER = {
  name: "",
  email: "",
  skills: "",
  exp: "",
  personality: "",
  sub: "Basic",
  subPeriod: "Monthly",
  status: "pending",
};

export const EMPTY_SCHOOL = {
  name: "",
  city: "",
  type: "",
  sub: "Basic",
  status: "pending",
  teachers: 0,
  rating: 0,
};

export const NAV = [
  { key: "dashboard",      label: "Dashboard",        icon: "LayoutDashboard" },
  { key: "teachers",       label: "Teachers",          icon: "Users" },
  { key: "schools",        label: "Schools",           icon: "Building2" },
  { key: "matching",       label: "Matching System",   icon: "Shuffle" },
  { key: "subscriptions",  label: "Subscriptions",     icon: "CreditCard" },
  { key: "feedback",       label: "Feedback",          icon: "Star" },
  { key: "notifications",  label: "Notifications",     icon: "Bell" },
];
